[project]
name = "unicall" # REQUIRED, is the only field that cannot be marked as dynamic.
version = "1.0.0" # REQUIRED, although can be dynamic
description = "A sample Python project"
readme = "README.md"